// Generated by Wrangler by running `wrangler types`

interface Env {
	CHARACTER_OWNERSHIP: KVNamespace;
	ACTIVE_SESSIONS: KVNamespace;
	SESSION_HISTORY: KVNamespace;
	SESSION_JWT_PUBLIC_KEY_BASE64: "<PLACEHOLDER>";
	SERVICE_API_JWT_PUBLIC_KEY_BASE64: "<PLACEHOLDER>";
	SESSION_NAMESPACE: DurableObjectNamespace<import("./src/index").AnimationSessionDO>;
}
